# Generated by Django 3.1.2 on 2021-01-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20180607_1711'),
        ('accounts', '0010_auto_20210102_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_employable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='personality',
            field=models.ManyToManyField(blank=True, null=True, to='personality.PersonalityType'),
        ),
    ]
