# Generated by Django 3.1.2 on 2021-01-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20180607_1711'),
        ('accounts', '0011_auto_20210103_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='personality',
            field=models.ManyToManyField(blank=True, to='personality.PersonalityType'),
        ),
    ]
